### ISSUE TITLE
Error in Buttons.py running on Manjaro Linux

### ISSUE THREAD

**Issue by JFincher42** [Abdur-rahmaanJ/hooman#25]
https://github.com/Abdur-rahmaanJ/hooman/blob/1ab113cd96111ab55ceacdc38ce996fbb71850a9/hooman/demos/Buttons.py#L45

Error with Hooman 0.3.6:

```
❯ /home/jon/git/hooman_test/.venv/bin/python3.8 /home/jon/git/hooman_test/hooman_test/test1.py
pygame 2.0.0 (SDL 2.0.12, python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/jon/git/hooman_test/hooman_test/test1.py", line 45, in <module>
    button1 = hapi.button(150, 150, "Click Me", grey_style)
  File "/home/jon/git/hooman_test/.venv/lib/python3.8/site-packages/hooman/hooman.py", line 334, in button
    b = Button(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'text'
```

**Comment by Abdur-rahmaanJ** [comment]
@JFincher42 see updated snippet on README, we forgot to update the demo!
